// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb3d2h0AJeO43cbjEJyLKcgFtQB3IkNf4',
    appId: '1:901313753130:web:03d94c2f84be25d6069353',
    messagingSenderId: '901313753130',
    projectId: 'reddit-clone-e6aa6',
    authDomain: 'reddit-clone-e6aa6.firebaseapp.com',
    storageBucket: 'reddit-clone-e6aa6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_aiLwGc_lAiqKwFrdAv2DWARhwrJ_Je8',
    appId: '1:901313753130:android:b262975650be9447069353',
    messagingSenderId: '901313753130',
    projectId: 'reddit-clone-e6aa6',
    storageBucket: 'reddit-clone-e6aa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz9WkNMaa4TwkstjiR7QS9uaS751AEJeQ',
    appId: '1:901313753130:ios:0fc7934ecdde3d1f069353',
    messagingSenderId: '901313753130',
    projectId: 'reddit-clone-e6aa6',
    storageBucket: 'reddit-clone-e6aa6.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz9WkNMaa4TwkstjiR7QS9uaS751AEJeQ',
    appId: '1:901313753130:ios:0fc7934ecdde3d1f069353',
    messagingSenderId: '901313753130',
    projectId: 'reddit-clone-e6aa6',
    storageBucket: 'reddit-clone-e6aa6.appspot.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb3d2h0AJeO43cbjEJyLKcgFtQB3IkNf4',
    appId: '1:901313753130:web:d72b3c8749d83b54069353',
    messagingSenderId: '901313753130',
    projectId: 'reddit-clone-e6aa6',
    authDomain: 'reddit-clone-e6aa6.firebaseapp.com',
    storageBucket: 'reddit-clone-e6aa6.appspot.com',
  );

}